@echo off
set "GlobalIni=%appdata%\obs-studio\global.ini"

echo [General]> "%GlobalIni%"
echo Pre19Defaults=false>> "%GlobalIni%"
echo Pre21Defaults=false>> "%GlobalIni%"
echo Pre23Defaults=false>> "%GlobalIni%"
echo Pre24.1Defaults=false>> "%GlobalIni%"
echo InstallGUID=1e050d84772f623e7f7dbc764e6c8e56edb60c0e>> "%GlobalIni%"
echo FirstRun=true>> "%GlobalIni%"
echo SkipUpdateVersion=452984833>> "%GlobalIni%"
echo ProcessPriority=Normal>> "%GlobalIni%"
echo BrowserHWAccel=false>> "%GlobalIni%"
echo LastVersion=453115908>> "%GlobalIni%"
echo CurrentTheme2=Moonlight>> "%GlobalIni%"
echo CurrentTheme3=Moonlight>> "%GlobalIni%"
echo EnableAutoUpdates=false>> "%GlobalIni%"
echo.>> "%GlobalIni%"
echo [Basic]>> "%GlobalIni%"
echo Profile=Default @Matishzz>> "%GlobalIni%"
echo ProfileDir=Default @Matishzz>> "%GlobalIni%"
echo SceneCollection=Matishzz>> "%GlobalIni%"
echo SceneCollectionFile=Matishzz>> "%GlobalIni%"
echo.>> "%GlobalIni%"
echo [BasicWindow]>> "%GlobalIni%"
echo gridMode=false>> "%GlobalIni%"
echo geometry=AdnQywADAAAAAAFyAAAAgQAABecAAAN5AAABcgAAAKAAAAXnAAADeQAAAAAAAAAAB4AAAAFyAAAAoAAABecAAAN5>> "%GlobalIni%"
echo DockState=AAAA/wAAAAD9AAAAAQAAAAMAAAR2AAABSfwBAAAABPwAAAAAAAABgAAAAYAA/////AEAAAAC+wAAABYAcwBvAHUAcgBjAGUAcwBEAG8AYwBrAQAAAAAAAACgAAAAoAD////7AAAAEgBtAGkAeABlAHIARABvAGMAawEAAACkAAAA3AAAANwA////+wAAABIAcwB0AGEAdABzAEQAbwBjAGsBAAABhAAAAk4AAAJOAP////sAAAAeAHQAcgBhAG4AcwBpAHQAaQBvAG4AcwBEAG8AYwBrAgAABLEAAAK4AAAAhAAAAAD8AAAD1gAAAKAAAACgAP////wCAAAAAvsAAAAUAHMAYwBlAG4AZQBzAEQAbwBjAGsBAAABeAAAAIEAAABTAP////sAAAAYAGMAbwBuAHQAcgBvAGwAcwBEAG8AYwBrAQAAAf0AAADEAAAAxAD///8AAAR2AAABXgAAAAQAAAAEAAAACAAAAAj8AAAAAA==>> "%GlobalIni%"
echo ExtraBrowserDocks=[]>> "%GlobalIni%"
echo PreviewEnabled=true>> "%GlobalIni%"
echo AlwaysOnTop=false>> "%GlobalIni%"
echo SceneDuplicationMode=true>> "%GlobalIni%"
echo SwapScenesMode=true>> "%GlobalIni%"
echo EditPropertiesMode=false>> "%GlobalIni%"
echo PreviewProgramMode=false>> "%GlobalIni%"
echo DocksLocked=false>> "%GlobalIni%"
echo WarnBeforeStartingStream=false>> "%GlobalIni%"
echo WarnBeforeStoppingStream=false>> "%GlobalIni%"
echo WarnBeforeStoppingRecord=false>> "%GlobalIni%"
echo HideProjectorCursor=false>> "%GlobalIni%"
echo ProjectorAlwaysOnTop=false>> "%GlobalIni%"
echo.>> "%GlobalIni%"

echo [ScriptLogWindow]>> "%GlobalIni%"
echo geometry=AdnQywACAAAAAAAAAAAAAAAAAlcAAAGPAAAAAAAAAAAAAAJXAAABjwAAAAAAAAAAB4A=>> "%GlobalIni%"
goto CreateDefault
exit