@echo off
set "folder=%appdata%\obs-studio\basic\profiles\936p 60fps"
set "Basic=%folder%\basic.ini"
md "%folder%" 2>nul
echo [General]>>"%basic%"
echo Name=936p 60fps>>"%basic%"

echo.>>"%basic%"

echo [Output]>>"%basic%"
echo Mode=Advanced>>"%basic%"
echo DelayEnable=false>>"%basic%"
echo DelayPreserve=true>>"%basic%"
echo Reconnect=true>>"%basic%"
echo RetryDelay=5>>"%basic%"
echo MaxRetries=25>>"%basic%"
echo BindIP=default>>"%basic%"
echo NewSocketLoopEnable=false>>"%basic%"
echo LowLatencyEnable=false>>"%basic%"

echo.>>"%basic%"

echo [AdvOut]>>"%basic%"
echo ApplyServiceSettings=true>>"%basic%"
echo UseRescale=false>>"%basic%"
echo VodTrackIndex=2>>"%basic%"
echo Encoder=jim_nvenc>>"%basic%"
echo RecType=Standard>>"%basic%"
echo RecFormat2=mp4>>"%basic%"
echo RecUseRescale=false>>"%basic%"
echo RecEncoder=jim_nvenc>>"%basic%"
echo FFOutputToFile=true>>"%basic%"
echo FFVBitrate=2500>>"%basic%"
echo FFVGOPSize=250>>"%basic%"
echo FFUseRescale=false>>"%basic%"
echo FFIgnoreCompat=false>>"%basic%"
echo FFABitrate=160>>"%basic%"
echo Track1Bitrate=160>>"%basic%"
echo Track2Bitrate=160>>"%basic%"
echo Track3Bitrate=160>>"%basic%"
echo Track4Bitrate=160>>"%basic%"
echo Track5Bitrate=160>>"%basic%"
echo Track6Bitrate=160>>"%basic%"
echo RecSplitFileTime=15>>"%basic%"
echo RecSplitFileSize=2048>>"%basic%"
echo RecRB=true>>"%basic%"
echo RecRBTime=120>>"%basic%"
echo RecRBSize=1024>>"%basic%"
echo AudioEncoder=ffmpeg_aac>>"%basic%"
echo RecAudioEncoder=ffmpeg_aac>>"%basic%"
echo RecSplitFileType=Time>>"%basic%"
echo FFFormat=>>"%basic%"
echo FFFormatMimeType=>>"%basic%"
echo FFVEncoderId=0>>"%basic%"
echo FFVEncoder=>>"%basic%"
echo FFAEncoderId=0>>"%basic%"
echo FFAEncoder=>>"%basic%"
echo RecFileNameWithoutSpace=true>>"%basic%"

echo.>>"%basic%"

echo [Video]>>"%basic%"
echo BaseCX=1664>>"%basic%"
echo BaseCY=936>>"%basic%"
echo OutputCX=1664>>"%basic%"
echo OutputCY=936>>"%basic%"
echo FPSCommon=60>>"%basic%"
echo FPSInt=30>>"%basic%"
echo FPSNum=30>>"%basic%"
echo ScaleType=bilinear>>"%basic%"
echo ColorFormat=NV12>>"%basic%"
echo ColorSpace=709>>"%basic%"
echo ColorRange=Partial>>"%basic%"
echo SdrWhiteLevel=300>>"%basic%"
echo HdrNominalPeakLevel=1000>>"%basic%"

echo.>>"%basic%"

echo [Audio]>>"%basic%"
echo MonitoringDeviceId=default>>"%basic%"
echo MonitoringDeviceName=default>>"%basic%"
echo SampleRate=48000>>"%basic%"
echo ChannelSetup=Stereo>>"%basic%"
echo MeterDecayRate=23.53>>"%basic%"

echo.>>"%basic%"

echo [Hotkeys]>>"%basic%"
echo ReplayBuffer={"ReplayBuffer.Save":[{"key":"OBS_KEY_F7"}]}>>"%basic%"
echo {"rate_control":"CQP","cqp":17,"preset2":"p4","tune":"ll","multipass":"disabled","profile":"main","psycho_aq":true} > "%folder%\recordEncoder.json"
echo {"preset2":"p4","tune":"ll","multipass":"disabled","psycho_aq":true} > "%folder%\streamEncoder.json"